# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
      - name: Run with Ant
        run: ant run
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: ba1-mp1
          path: bin